# Embeds lib/*.khu into a generated C++ source.
#
# The standard library is part of the toolchain, not a file the user has to
# have installed, so `khudra` carries it. Run as:
#
#   cmake -DOUTPUT=<file.cpp> -DSOURCES="a.khu;b.khu" -P embed_stdlib.cmake
if(NOT DEFINED OUTPUT OR NOT DEFINED SOURCES)
    message(FATAL_ERROR "embed_stdlib.cmake needs OUTPUT and SOURCES")
endif()

set(generated "// Generated by scripts/embed_stdlib.cmake -- do not edit.\n")
string(APPEND generated "#include \"sema/stdlib_sources.h\"\n\n")
string(APPEND generated "namespace khu::sema {\n\n")
string(APPEND generated "namespace {\n\n")

set(index 0)
set(table "")
foreach(source ${SOURCES})
    get_filename_component(name "${source}" NAME)
    file(READ "${source}" contents)
    string(APPEND generated "const char kSource${index}[] = R\"KHUDRA_STDLIB(${contents})KHUDRA_STDLIB\";\n\n")
    string(APPEND table "    StdlibFile{\"lib/${name}\", kSource${index}},\n")
    math(EXPR index "${index} + 1")
endforeach()

string(APPEND generated "const StdlibFile kFiles[] = {\n${table}};\n\n")
string(APPEND generated "}  // namespace\n\n")
string(APPEND generated "const StdlibFile* stdlib_files() { return kFiles; }\n")
string(APPEND generated "std::size_t stdlib_file_count() { return ${index}; }\n\n")
string(APPEND generated "}  // namespace khu::sema\n")

file(WRITE "${OUTPUT}" "${generated}")
