# Embeds src/native/host/khu_native_abi.h into a generated C++ source.
#
# The emitted C carries its own copy of the ABI header so a translation unit is
# self-contained -- `khudra build` cannot assume the Khudra source tree is still
# on disk. Embedding keeps one source of truth: the header the host compiles
# against is the header the generated C sees.
#
#   cmake -DOUTPUT=<file.cpp> -DHEADER=<khu_native_abi.h> -P embed_native_abi.cmake
if(NOT DEFINED OUTPUT OR NOT DEFINED HEADER)
    message(FATAL_ERROR "embed_native_abi.cmake needs OUTPUT and HEADER")
endif()

file(READ "${HEADER}" contents)

set(generated "// Generated by scripts/embed_native_abi.cmake -- do not edit.\n")
string(APPEND generated "#include \"cemit/cemit.h\"\n\n")
string(APPEND generated "namespace khu::native {\n\n")
string(APPEND generated "namespace {\n")
string(APPEND generated "const char kAbiSource[] = R\"KHUDRA_ABI(${contents})KHUDRA_ABI\";\n")
string(APPEND generated "}  // namespace\n\n")
string(APPEND generated "const char* native_abi_source() { return kAbiSource; }\n\n")
string(APPEND generated "}  // namespace khu::native\n")

file(WRITE "${OUTPUT}" "${generated}")
